services:
  _defaults: { public: true }

  product.controller:
    class: Coolblue\TDD\Infrastructure\Product\GetProductController
    arguments:
      - '@http.response.factory'
      - '@product.product_information_service'

  product.product_information_service:
    class: Coolblue\TDD\Infrastructure\Product\ProductInformationService
