services:
  _defaults: { public: true }

  product.accessories.controller:
    class: Coolblue\TDD\Infrastructure\Product\GetProductAccessoriesController
    arguments:
      - '@http.response.factory'
