product.information:
  path: /product/{productId}
  controller: 'product.controller'
  requirements:
    productId: '\d+'
  methods: GET

product.accessories:
  path: /product/{productId}/accessories
  controller: 'product.accessories.controller'
  requirements:
    productId: '\d+'
  methods: GET
